name: connect_mi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  go_router: ^14.1.4
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  flutter_circle_color_picker: ^0.3.0
  gradient_slider: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

  fonts:
    - family: Aldrich
      fonts:
        - asset: assets/fonts/Aldrich-Regular.ttf
